### ISSUE TITLE
Some comments

### ISSUE THREAD

**Issue by syao13** [rmflight/waitcopy#8]
* files with the same base name that are different -- Not clear what it means.

-- Some dependents or codes I need to install/load/run besides what's in the example:

* Installation
install.packages("devtools")
library(devtools)
library(rprojroot)

* assuming you are in the package directory
setwd(.libPaths())
setwd("waitcopy")

* Alternatives (not run)
-- So I didn't not run after this.

-- Other than above mentioned, description is clear, code runs well, and results I got are the same as the results in the example.

**Comment by rmflight** [comment]
These should be handled by the new version. Could you double check that the definitions help, and that the example is better now, and if so, close the issue @syao13 ??

Thanks!

**Comment by syao13** [comment]
Yep, everything looks good now.
